name = "GridMethod"
uuid = "86dfab32-2c2d-4347-886c-662f6c611e7a"
authors = ["Laura Brustenga i Moncusí", "Chris La Valle" ,"Josué Tonelli-Cueto"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"

[targets]
test = ["Test", "HomotopyContinuation"]
